[package]
name = "VaultAPI-Client"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.0"
base64 = "0.21.0"
sha2 = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ring = "0.17.8"
digest = "0.10.7"
aead = "0.5.2"
